In [1]:
import numpy as np
import import_ipynb
from Q1 import lu_decomposition, substitution, gauss_elimanation

In [2]:
A = np.array([
    [4,8,4,0],
    [1,4,7,2],
    [1,5,4,-3],
    [1,3,0,-2]
], dtype=np.float64)

In [3]:
L, U = lu_decomposition(A)

print("Matrix L:\n")
print(L)
print("\n\nMatrix U:\n")
print(U)


m, n = A.shape
I = np.eye(n)
# B is the inverse of A
B = np.zeros_like(A, dtype=np.float64)


# calculate columns of B
for i in range(n):
    # get the i column of I
    c = I[:,i:i+1]
    z = substitution(L, c)
    i_col_B = substitution(U, z)
    B[:,i:i+1] = i_col_B
    

A_dot_B = np.dot(B,A).astype(np.int64)    
print("\n\n  -1")
print("AA \t- Matrix multiplication of A and its inverse:")
print(A_dot_B)

Matrix L:

[[1.         0.         0.         0.        ]
 [0.25       1.         0.         0.        ]
 [0.25       1.5        1.         0.        ]
 [0.25       0.5        0.66666667 1.        ]]


Matrix U:

[[ 4.  8.  4.  0.]
 [ 0.  2.  6.  2.]
 [ 0.  0. -6. -6.]
 [ 0.  0.  0.  1.]]


  -1
AA 	- Matrix multiplication of A and its inverse:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
